CREATE TABLE IF NOT EXISTS `adressen` (
    `id` int unsigned NOT NULL AUTO_INCREMENT,
    `AdrNr` int NOT NULL,
    `SBegrAdr` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `Anrede` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `Titel` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `Vorname` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `Name1` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `Name2` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `Name3` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `Strasse` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `Land` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `PLZ` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `Ort` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `Zustellpostamt` int NOT NULL DEFAULT '0',
    `GebDat1` date DEFAULT NULL,
    `GebDat2` date DEFAULT NULL,
    `SBrief_JN` bit(1) NOT NULL DEFAULT b'0',
    `SF1` varchar(3) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `SF2` varchar(3) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `SF3` varchar(3) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `SF4` varchar(3) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `SF5` varchar(3) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `SF6` varchar(3) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `SF7` varchar(3) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `SF8` varchar(3) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `SF9` varchar(3) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `SF10` varchar(3) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `BriefAnZeil1` varchar(50) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `BriefAnZeil2` varchar(50) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `Geburtsname` varchar(50) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `BerufsBez` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci DEFAULT NULL,
    `SterbeDat1` date DEFAULT NULL,
    `SterbeDat2` date DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `AdrNr_E` (`AdrNr`),
    KEY `Suchbegr_M` (`SBegrAdr`),
    KEY `Name1_M` (`Name1`),
    KEY `Gebname_M` (`Geburtsname`),
    KEY `PLZ_M` (`PLZ`),
    KEY `Ort_M` (`Ort`),
    KEY `SonderfktM` (`SF1`,`SF2`,`SF3`,`SF4`,`SF5`,`SF6`,`SF7`,`SF8`,`SF9`,`SF10`)
    ) ENGINE=InnoDB AUTO_INCREMENT=3093 DEFAULT CHARSET=latin1;