CREATE TABLE IF NOT EXISTS `adressen` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `nummer` int(11) NOT NULL,
    `suchbegriff` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `anrede` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `titel` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `vorname` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `name1` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `name2` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `name3` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `strasse` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `land` varchar(3) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `plz` varchar(6) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `ort` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `zustellpostamt` smallint(6) unsigned NOT NULL DEFAULT 0,
    `geburtsdatum1` int(11) NOT NULL DEFAULT 0,
    `geburtsdatum2` int(11) NOT NULL DEFAULT 0,
    `is_serienbrief` bit(1) NOT NULL DEFAULT b'0',
    `sonderfunktion1` varchar(3) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `sonderfunktion2` varchar(3) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `sonderfunktion3` varchar(3) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `sonderfunktion4` varchar(3) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `sonderfunktion5` varchar(3) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `sonderfunktion6` varchar(3) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `sonderfunktion7` varchar(3) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `sonderfunktion8` varchar(3) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `sonderfunktion9` varchar(3) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `sonderfunktion10` varchar(3) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `brief_anrede_zeile1` varchar(50) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `brief_anrede_zeile2` varchar(50) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `geburtsname` varchar(50) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `berufsbezeichnung` varchar(30) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
    `sterbedatum1` int(11) NOT NULL DEFAULT 0,
    `sterbedatum2` int(11) NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `AdrNr_E` (`nummer`),
    KEY `Suchbegr_M` (`suchbegriff`),
    KEY `Name1_M` (`name1`),
    KEY `Gebname_M` (`geburtsname`),
    KEY `PLZ_M` (`plz`),
    KEY `Ort_M` (`ort`),
    KEY `SonderfktM` (`sonderfunktion1`,`sonderfunktion2`,`sonderfunktion3`,`sonderfunktion4`,`sonderfunktion5`,`sonderfunktion6`,`sonderfunktion7`,`sonderfunktion8`,`sonderfunktion9`,`sonderfunktion10`)
    ) ENGINE=InnoDB AUTO_INCREMENT=3094 DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;